SV-Winter-BootCamp-Team-C/frontend

Dockerfile
Dockerfile 작성 완료
Closes #5 
<br>
=> chore: Dockerfile 세팅

src/Router.tsx, src/assets/navAnalysis.svg, src/components/common/Navbar.tsx, src/components/survey/SurveyCover.tsx, src/components/survey/SurveyCoverMenu.tsx, src/components/survey/SurveyForm.tsx, src/global.css
Navbar 수정
완료된 후 캡쳐
Closes #24 
<br>
=> bug: navbar 색상 수정

package.json
설명을 작성하세요.
완료된 후 캡쳐
Closes #(이슈번호)
<br>
=> fix: package.json 수정

src/pages/ResponseForm.tsx
:ResponseForm Page ScrollBar add
- [] ResponseForm Page ScrollBar add
Closes #37 
<br>
=> Feat:ResponseForm ScrollBar add

package-lock.json, package.json, src/components/common/Alert.tsx, src/components/common/Button.tsx, src/components/survey/SurveyForm.tsx, src/global.css, src/layout/MainLayout.tsx, src/pages/AllForm.tsx, src/pages/Login.tsx, src/pages/MyForm.tsx, src/pages/Signup.tsx, src/pages/Start.tsx
설명을 작성하세요.
- [] todo
- [] todo
완료된 후 캡쳐
Closes #(이슈번호)
<br>
=> feat: transition 적용

src/Router.tsx, src/components/common/Button.tsx, src/components/surveyResult/Response/Response.tsx
설문 결과 분석 페이지 버튼 위치 수정
- [] todo
- [] todo
완료된 후 캡쳐
Closes #46 
<br>
=> fix: 버튼 위치 수정

.eslintrc.cjs, src/App.tsx, src/queryClient.ts
=> chore: react-query 전역 에러 핸들링 코드 추가

package-lock.json, package.json, src/components/common/Navbar.tsx, src/pages/Login.tsx, src/store/AuthStore.tsx, src/store/NavbarStore.tsx
설명을 작성하세요.
- [] todo
- [] todo
완료된 후 캡쳐
Closes #55 
<br>
=> chore: zustand 세팅 및 설정 완료

src/App.tsx, src/Router.tsx, src/components/common/Loading.tsx, src/components/common/MyProfileModal.tsx, src/layout/MainLayout.tsx
=> design: 로딩중 컴포넌트

src/components/responsetype/ResponseCheckBox.tsx, src/components/responsetype/ResponseDropDown.tsx, src/components/responsetype/ResponseMultipleChoice.tsx, src/components/responsetype/ResponseSubjective.tsx, src/components/staticresponse/StaticCheckBox.tsx, src/components/staticresponse/StaticDropDown.tsx, src/components/staticresponse/StaticMultipleChoice.tsx, src/components/staticresponse/StaticSubjective.tsx, src/components/survey/SurveyForm.tsx, src/components/surveyResult/Question/PieChart.tsx, src/components/surveyResult/Question/Question.tsx, src/components/surveyResult/Question/SubjectQuestion.tsx, src/pages/MyAnswer.tsx, src/pages/ResponseForm.tsx, src/queryClient.ts, src/types/questionData.ts, src/types/survey.ts
type 스네이크 케이스 -> 카멜 케이스
완료된 후 캡쳐
Closes #48 
<br>
=> fix: type 값 수정

src/Router.tsx, src/components/common/MyProfileModal.tsx, src/components/common/ShareMailModal.tsx, src/components/survey/SurveyCoverMenu.tsx
설명을 작성하세요.
완료된 후 캡쳐
Closes #52 
<br>
=> Design:공유이메일입력창 만들기

src/api/signup.ts, src/pages/Login.tsx, src/pages/Signup.tsx
회원가입시 이메일 중복 확인 기능 추가
Closes #62 
<br>
=> feat: 회원가입시 이메일 중복 확인 기능 추가

src/api/myprofile.ts, src/components/common/MyProfileModal.tsx, src/components/common/Navbar.tsx, src/pages/Login.tsx
Profile 클릭 시 내 정보 조회하기
완료된 후 캡쳐
Closes #64
<br>
=> Feat: 설문지 스타일/문항생성페이지 기능구현

src/Router.tsx, src/api/responseform.ts, src/components/responsetype/ResponseCheckBox.tsx, src/components/responsetype/ResponseDropDown.tsx, src/components/responsetype/ResponseMultipleChoice.tsx, src/components/responsetype/ResponseSubjective.tsx, src/pages/MyAnswer.tsx, src/pages/ResponseForm.tsx, src/queryClient.ts, src/types/questionData.ts
설문 응답, 제출
완료된 후 캡쳐
Closes #65
<br>
=> feat: 설문 응답, 제출

src/Router.tsx, src/api/getResult.ts, src/components/common/Alert.tsx, src/components/common/Button.tsx, src/components/common/Loading.tsx, src/components/survey/SurveyCover.tsx, src/components/survey/SurveyCoverMenu.tsx, src/components/survey/SurveyForm.tsx, src/components/surveyResult/Question/PieChart.tsx, src/components/surveyResult/Question/Question.tsx, src/components/surveyResult/Question/SubjectQuestion.tsx, src/components/surveyResult/Response/Response.tsx, src/pages/ResultPage.tsx, src/types/answerData.ts, src/types/questionData.ts, src/types/survey.ts
설명을 작성하세요.
완료된 후 캡쳐
Closes #70 
<br>
=> feat: 설문 결과 페이지 API 연동 완료

src/Router.tsx, src/components/survey/SurveyForm.tsx
설명을 작성하세요.
완료된 후 캡쳐
Closes #74 
<br>
=> fix: 설문 결과 분석 경로 수정

src/api/surveyMenu.ts, src/components/common/Loading.tsx, src/components/common/ShareMailModal.tsx, src/components/survey/SurveyCoverMenu.tsx
=> feat: 설문 url 공유 기능

src/api/myprofile.ts, src/components/common/MyProfileModal.tsx, src/components/common/Navbar.tsx, src/store/AuthStore.tsx
비밀번호 변경, 로그아웃 기능
Closes #80 
<br>
=> feat: 비밀번호 변경, 로그아웃 기능

src/api/getForm.ts, src/components/survey/SurveyForm.tsx, src/hooks/usePaginationSurveyList.ts, src/pages/AllForm.tsx, src/pages/MyResponse.tsx, src/types/questionData.ts, src/types/survey.ts
All 페이지 검색 기능
완료된 후 캡쳐
Closes #85
<br>
=> feat:All 페이지 검색 기능

src/pages/Create.tsx
설명을 작성하세요.
- [] todo
- [] todo
완료된 후 캡쳐
Closes #90
<br>
=> bug:이미지 검색 충돌 수정
